#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIController_CombatHeli

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AIController_CombatHeli.BP_AIController_CombatHeli_C
// 0x0020 (0x0558 - 0x0538)
class ABP_AIController_CombatHeli_C final : public APalAIController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0538(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                SpawnedLocation;                                   // 0x0540(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_AIController_CombatHeli(int32 EntryPoint);
	void On_Dead(const struct FPalDeadInfo& DeadInfo);
	void ReceivePossess(class APawn* PossessedPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AIController_CombatHeli_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AIController_CombatHeli_C")
	}
	static class ABP_AIController_CombatHeli_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AIController_CombatHeli_C>();
	}
};
DUMPER7_ASSERTS_ABP_AIController_CombatHeli_C;

}

