#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Action_NPC_MeleeAttackWithGun

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Action_NPC_MeleeAttackWithGun.BP_Action_NPC_MeleeAttackWithGun_C
// 0x0010 (0x0170 - 0x0160)
class UBP_Action_NPC_MeleeAttackWithGun_C final : public UPalActionBase
{
public:
	uint8                                         Pad_158[0x8];                                      // 0x0158(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0160(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Action_NPC_MeleeAttackWithGun(int32 EntryPoint);
	void OnBeginAction();
	void OnBlendOut_18F6DF3D47B5756AF6D31082F414DE7D(class FName NotifyName);
	void OnCompleted_18F6DF3D47B5756AF6D31082F414DE7D(class FName NotifyName);
	void OnInterrupted_18F6DF3D47B5756AF6D31082F414DE7D(class FName NotifyName);
	void OnNotifyBegin_18F6DF3D47B5756AF6D31082F414DE7D(class FName NotifyName);
	void OnNotifyEnd_18F6DF3D47B5756AF6D31082F414DE7D(class FName NotifyName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Action_NPC_MeleeAttackWithGun_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Action_NPC_MeleeAttackWithGun_C")
	}
	static class UBP_Action_NPC_MeleeAttackWithGun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Action_NPC_MeleeAttackWithGun_C>();
	}
};
DUMPER7_ASSERTS_UBP_Action_NPC_MeleeAttackWithGun_C;

}

