#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIAction_FriendlyLookat

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_AIAction_CanCombatBase_classes.hpp"
#include "AIModule_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AIAction_FriendlyLookat.BP_AIAction_FriendlyLookat_C
// 0x0018 (0x0178 - 0x0160)
class UBP_AIAction_FriendlyLookat_C final : public UBP_AIAction_CanCombatBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_AIAction_FriendlyLookat_C;       // 0x0160(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AActor*                                 TargetActor;                                       // 0x0168(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsFinished;                                        // 0x0170(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanLookatPal;                                      // 0x0171(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Rotating;                                          // 0x0172(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SingleEffectAble;                                  // 0x0173(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ActionFinished(class APawn* ControlledPawn, EPawnActionResult WithResult);
	void ActionTick(class APawn* ControlledPawn, float DeltaSeconds);
	void ExecuteUbergraph_BP_AIAction_FriendlyLookat(int32 EntryPoint);
	void ActionStart(class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AIAction_FriendlyLookat_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AIAction_FriendlyLookat_C")
	}
	static class UBP_AIAction_FriendlyLookat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AIAction_FriendlyLookat_C>();
	}
};
DUMPER7_ASSERTS_UBP_AIAction_FriendlyLookat_C;

}

