#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIAction_LookSideMove

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AIAction_LookSideMove.BP_AIAction_LookSideMove_C
// 0x0060 (0x0190 - 0x0130)
class UBP_AIAction_LookSideMove_C final : public UPalAIActionBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0130(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                SelfToTarget;                                      // 0x0138(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Rate;                                              // 0x0150(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Right;                                             // 0x0158(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsRightMoving;                                     // 0x0160(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_161[0x7];                                      // 0x0161(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CurrentMoveGoal;                                   // 0x0168(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                          SelfActor;                                         // 0x0180(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCheckWalkableSuccess;                            // 0x0188(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ActionAbort(class APawn* ControlledPawn);
	void ActionFinished(class APawn* ControlledPawn, EPawnActionResult WithResult);
	void ActionPause(class APawn* ControlledPawn);
	void ActionPostTick(class APawn* ControlledPawn, float DeltaSeconds);
	void ActionResume(class APawn* ControlledPawn);
	void ActionStart(class APawn* ControlledPawn);
	void ActionTick(class APawn* ControlledPawn, float DeltaSeconds);
	void ActionTickAnyThread(class APawn* ControlledPawn, float DeltaSeconds);
	void CheckWalkable(bool IsRight, bool* Success, struct FVector* GoalPos);
	void ExecuteUbergraph_BP_AIAction_LookSideMove(int32 EntryPoint);
	void OnChildActionFinished(class UPawnAction* action, EPawnActionResult WithResult);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AIAction_LookSideMove_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AIAction_LookSideMove_C")
	}
	static class UBP_AIAction_LookSideMove_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AIAction_LookSideMove_C>();
	}
};
DUMPER7_ASSERTS_UBP_AIAction_LookSideMove_C;

}

