#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FunnelCharacter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FunnelCharacter.BP_FunnelCharacter_C
// 0x0020 (0x0A60 - 0x0A40)
class ABP_FunnelCharacter_C final : public APalFunnelCharacter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPalNavigationInvokerComponent*         PalNavigationInvoker;                              // 0x0A48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPalFacialComponent*                    PalFacial;                                         // 0x0A50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_FunnelCharacter(int32 EntryPoint);
	void OnActive(bool NoEffect);
	void OnInactive(bool NoEffect);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void SetLocationNearTrainer();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FunnelCharacter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FunnelCharacter_C")
	}
	static class ABP_FunnelCharacter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FunnelCharacter_C>();
	}
};
DUMPER7_ASSERTS_ABP_FunnelCharacter_C;

}

