#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalGameInstance

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PalGameInstance.BP_PalGameInstance_C
// 0x00D0 (0x09B8 - 0x08E8)
class UBP_PalGameInstance_C final : public UPalGameInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ULoadingProcessTask*                    CurrentLoadingTask;                                // 0x08F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UPalHUDDispatchParameter_FadeWidget*    LoadingFadeParameter;                              // 0x08F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UWorld>                  LoadWorld;                                         // 0x0900(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash)
	bool                                          ShowedCharaMake;                                   // 0x0930(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_931[0x7];                                      // 0x0931(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftClassPtr<class UClass>                   OpeningActor;                                      // 0x0938(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   CutsceneName;                                      // 0x0968(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalCutsceneActor*                      OpeningCutscene;                                   // 0x0970(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FName                                   flagName;                                          // 0x0978(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         PlayingID;                                         // 0x0980(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_984[0x4];                                      // 0x0984(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDataTableRowHandle                    CreateSessionErrorMsgId;                           // 0x0988(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FDataTableRowHandle                    CreateSessionErrorMsgId_Console;                   // 0x0998(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          IsStartingGame;                                    // 0x09A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9A9[0x3];                                      // 0x09A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   UIInputBlockFlagName;                              // 0x09AC(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BP_PalGameInstance_AutoGenFunc(bool bResult);
	void Completed_32AFD11A49E65B7255FF4BA375D305CC(bool IsSuccess, const class FString& ErrorStr);
	void ExecuteUbergraph_BP_PalGameInstance(int32 EntryPoint);
	void IsDeadInHardcore(bool* Result);
	void LoadingFinished();
	void LoadLevel(const TSoftObjectPtr<class UWorld> Level, const class FString& Options, bool AutoClose);
	void OnCloseMap(class UPalHUDDispatchParameterBase* Param);
	void OnCompleteSetup();
	void OnFinishCutscene(bool IsSkipped);
	void OnPSNChatDisabled(bool bResult);
	void OnShowSelectRespawnMap();
	void OverrideLoadMap(const TSoftObjectPtr<class UWorld>& World);
	void SetActivePlayerActor(bool Active);
	void SetPlayerSelectMap(bool IsSelecting);
	void SetupGameInit();
	void ShowCharacterMakeScreen();
	void StartGame(bool bNewGame, bool bListenServer, bool bCrossPlay);
	void StartLoading(const class UWBP_LoadingScreen_Transition_C*& CurrentLoadingWidget);
	void StartOpening();
	void カスタムイベント(bool bResult);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PalGameInstance_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PalGameInstance_C")
	}
	static class UBP_PalGameInstance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PalGameInstance_C>();
	}
};
DUMPER7_ASSERTS_UBP_PalGameInstance_C;

}

