#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PalBossBattleManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PalBossBattleManager.BP_PalBossBattleManager_C
// 0x0008 (0x0238 - 0x0230)
class UBP_PalBossBattleManager_C final : public UPalBossBattleManager
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0230(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void DisableSky(bool Activce, class APPSkyCreator* Sky);
	void DisableSkyCreator(bool Disable);
	void ExecuteUbergraph_BP_PalBossBattleManager(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PalBossBattleManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PalBossBattleManager_C")
	}
	static class UBP_PalBossBattleManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PalBossBattleManager_C>();
	}
};
DUMPER7_ASSERTS_UBP_PalBossBattleManager_C;

}

