#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Status_RaidBossModeChange

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Status_RaidBossModeChange.BP_Status_RaidBossModeChange_C
// 0x0090 (0x00D8 - 0x0048)
class UBP_Status_RaidBossModeChange_C : public UPalStatusBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0048(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        ReGeneTime;                                        // 0x0050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        ReGeneRate;                                        // 0x0058(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Timer;                                             // 0x0060(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<EPalStatusID>                          IgnoreStatusID;                                    // 0x0068(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FPalRaidBossSpawnInfo                  Boss_Info;                                         // 0x0078(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void CompEvent(class APalCharacter* InCharacter);
	void ExecuteUbergraph_BP_Status_RaidBossModeChange(int32 EntryPoint);
	void FindModeChangeVisualEffectType(EPalElementType Element, EPalVisualEffectID* VisualEffect);
	void FindRaidBossData(struct FPalRaidBossSpawnInfo* BossInfo);
	void OnBeginStatus();
	void OnEndStatus();
	void SetupStatus();
	void TickStatus(float DeltaTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Status_RaidBossModeChange_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Status_RaidBossModeChange_C")
	}
	static class UBP_Status_RaidBossModeChange_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Status_RaidBossModeChange_C>();
	}
};
DUMPER7_ASSERTS_UBP_Status_RaidBossModeChange_C;

}

