#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillEffect_GeneralWork

#include "Basic.hpp"

#include "BP_SkillEffectBase_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SkillEffect_GeneralWork.BP_SkillEffect_GeneralWork_C
// 0x0038 (0x03F8 - 0x03C0)
class ABP_SkillEffect_GeneralWork_C final : public ABP_SkillEffectBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_SkillEffect_GeneralWork_C;       // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USphereComponent*                       Sphere;                                            // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               PS_Scratch2;                                       // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               PS_Scratch1;                                       // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               PS_Scratch;                                        // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        StartCollisionTime;                                // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        EndCollisionTime;                                  // 0x03F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void EnableCollision();
	void EndCollision();
	void ExecuteUbergraph_BP_SkillEffect_GeneralWork(int32 EntryPoint);
	void SetupCollision(const struct FVector& TargetLocationPoint, const struct FVector& ImpactPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SkillEffect_GeneralWork_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SkillEffect_GeneralWork_C")
	}
	static class ABP_SkillEffect_GeneralWork_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SkillEffect_GeneralWork_C>();
	}
};
DUMPER7_ASSERTS_ABP_SkillEffect_GeneralWork_C;

}

