#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock

#include "Basic.hpp"

#include "BP_SkillEffectBase_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock.BP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock_C
// 0x0028 (0x03E8 - 0x03C0)
class ABP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock_C final : public ABP_SkillEffectBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock_C; // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCapsuleComponent*                      TraceBlockCollision;                               // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCapsuleComponent*                      BlockCollision;                                    // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Niagara;                                           // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        Life;                                              // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void EndLife();
	void ExecuteUbergraph_BP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock(int32 EntryPoint);
	void FadeOutEffect(double DeltaSecond);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock_C")
	}
	static class ABP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock_C>();
	}
};
DUMPER7_ASSERTS_ABP_UniqueSkillEffect_LegendDeer_RadiantPurge_Rock_C;

}

