#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CharaCre_ScrollBoxContent_Voice

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "WBP_CharaCre_ScrollBoxContentBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CharaCre_ScrollBoxContent_Voice.WBP_CharaCre_ScrollBoxContent_Voice_C
// 0x00C0 (0x04E8 - 0x0428)
class UWBP_CharaCre_ScrollBoxContent_Voice_C final : public UWBP_CharaCre_ScrollBoxContentBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0428(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWrapBox*                               WrapBox_Body;                                      // 0x0430(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(int32 VoiceID)> OnChangedVoiceID;                                  // 0x0438(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UAkAudioEvent*>                  SampleVoiceArray;                                  // 0x0448(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<int32, int32>                            PlayVoiceMap;                                      // 0x0458(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         VoiceCount;                                        // 0x04A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4AC[0x4];                                      // 0x04AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWBP_CharaCre_BodyTypeButton_C*> VoiceButtons;                                      // 0x04B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UWBP_CharaCre_BodyTypeButton_C*         LastClickedVoiceTypeButton;                        // 0x04C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(int32 VoiceID)> OnHoveredVoiceButton;                              // 0x04C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnUnhoveredVoiceButton;                            // 0x04D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ApplyMakeInfo(const struct FPalPlayerDataCharacterMakeInfo& MakeInfo);
	void Construct();
	void ExecuteUbergraph_WBP_CharaCre_ScrollBoxContent_Voice(int32 EntryPoint);
	void GetRestoreFocusTarget(class UWidget** Widget);
	void OnClickedVoiceTypeButton(class UWBP_CharaCre_BodyTypeButton_C* Widget);
	void OnHoveredVoiceTypeButton(class UWBP_CharaCre_BodyTypeButton_C* Widget);
	void OnUnhoveredVoiceTypeButton();
	void Play_Sample_Voice(int32 VoiceID);
	void GetTopFocusTarget(class UWidget** Widget);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CharaCre_ScrollBoxContent_Voice_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CharaCre_ScrollBoxContent_Voice_C")
	}
	static class UWBP_CharaCre_ScrollBoxContent_Voice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CharaCre_ScrollBoxContent_Voice_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CharaCre_ScrollBoxContent_Voice_C;

}

