#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LoupeBase

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_LoupeBase.WBP_LoupeBase_C
// 0x0030 (0x0488 - 0x0458)
class UWBP_LoupeBase_C : public UPalUIOffScreenLoupeBase
{
public:
	struct FVector2D                              targetPosition;                                    // 0x0458(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              NowPosition;                                       // 0x0468(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          isFirstUpdate;                                     // 0x0478(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          isInterpolationTranslate;                          // 0x0479(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_47A[0x6];                                      // 0x047A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        interpolationRate;                                 // 0x0480(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AdjustAlpha(const struct FVector2D& finalScreenPos, double* Alpha);
	void GetLoupeWidgetSize(struct FVector2D* widgetSize_0);
	void GetTranslationTarget(class UWidget** Widget);
	void RoundScreenPosition(const struct FVector2D& ScreenPosition, struct FVector2D* calcedPosition);
	void SetFinalWidgetOpacity(double calcedOpacity);
	void UpdateArrowImageAngle(double newAngle);
	void UpdateLoupeTranslation();
	void UpdatePositionAndVisibility(double Dot, const struct FVector& rootLocation, const struct FVector& TargetLocation);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_LoupeBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_LoupeBase_C")
	}
	static class UWBP_LoupeBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_LoupeBase_C>();
	}
};
DUMPER7_ASSERTS_UWBP_LoupeBase_C;

}

