#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_GlobalBoxPalList

#include "Basic.hpp"

#include "Pal_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.SetupForBP
// 0x0004 (0x0004 - 0x0000)
struct WBP_GlobalBoxPalList_C_SetupForBP final
{
public:
	int32                                         CallFunc_GetMaxPageNum_ReturnValue;                // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_SetupForBP;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.SetSortButtonEnable
// 0x0001 (0x0001 - 0x0000)
struct WBP_GlobalBoxPalList_C_SetSortButtonEnable final
{
public:
	bool                                          IsEnable;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_SetSortButtonEnable;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.Set Enable Page Control Action
// 0x0002 (0x0002 - 0x0000)
struct WBP_GlobalBoxPalList_C_Set_Enable_Page_Control_Action final
{
public:
	bool                                          bIsEnableAction;                                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidChangePageInputAction_bValidAction; // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_Set_Enable_Page_Control_Action;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.RefreshCurrentPage
// 0x0040 (0x0040 - 0x0000)
struct WBP_GlobalBoxPalList_C_RefreshCurrentPage final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetCurrentPage_CurrentPageNum;            // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UWBP_PalCommonCharacterSlotButton_C*> CallFunc_GetCurrentDisplaySlotWidgets_SlotWidgets; // 0x0010(0x0010)(ReferenceParm, ContainsInstancedReference)
	class UWBP_PalCommonCharacterSlotButton_C*    CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalIndividualCharacterSlot*            CallFunc_GetTargetSlot_targetSlot;                 // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_RefreshCurrentPage;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.OnClosedSortWindow
// 0x0008 (0x0008 - 0x0000)
struct WBP_GlobalBoxPalList_C_OnClosedSortWindow final
{
public:
	class UPalHUDDispatchParameterBase*           Param_0;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_OnClosedSortWindow;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.ExecuteUbergraph_WBP_GlobalBoxPalList
// 0x00B8 (0x00B8 - 0x0000)
struct WBP_GlobalBoxPalList_C_ExecuteUbergraph_WBP_GlobalBoxPalList final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_NewSlot;                // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_NowPage;                // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PalCommonCharacterSlotButton_C*    K2Node_DynamicCast_AsWBP_Pal_Common_Character_Slot_Button; // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UPalIndividualCharacterSlot*>    CallFunc_GetDummyPageSlots_OutSlots;               // 0x0028(0x0010)(ReferenceParm)
	bool                                          CallFunc_GetDummyPageSlots_ReturnValue;            // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPalHUDService*                         CallFunc_GetHUDService_ReturnValue;                // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_Widget_1;               // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPalHUDDispatchParameter_CharacterContainerSort* CallFunc_SpawnObject_ReturnValue;         // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGuid                                  CallFunc_Push_ReturnValue;                         // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPalContainerId                        CallFunc_GetGPSContainerId_OutId;                  // 0x0068(0x0010)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetGPSContainerId_ReturnValue;            // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_Widget_2;               // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_Widget_3;               // 0x0088(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalItemSlotPressType                         K2Node_ComponentBoundEvent_pressType;              // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x3];                                       // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UPalHUDDispatchParameterBase* Param)> K2Node_CreateDelegate_OutputDelegate; // 0x0094(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_PalCharacterSlotButtonBase_C*      K2Node_ComponentBoundEvent_Widget;                 // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_IsEnable;                       // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_ExecuteUbergraph_WBP_GlobalBoxPalList;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_6_OnRightClickedSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_6_OnRightClickedSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_6_OnRightClickedSlot__DelegateSignature;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_5_OnCreatedNewSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_5_OnCreatedNewSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      NewSlot;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_5_OnCreatedNewSlot__DelegateSignature;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_3_OnUpdatedPage__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_3_OnUpdatedPage__DelegateSignature final
{
public:
	int32                                         NowPage;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_3_OnUpdatedPage__DelegateSignature;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_2_OnUnhoveredSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_2_OnUnhoveredSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_2_OnUnhoveredSlot__DelegateSignature;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_1_OnHoveredSlot__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_1_OnHoveredSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_1_OnHoveredSlot__DelegateSignature;

// Function WBP_GlobalBoxPalList.WBP_GlobalBoxPalList_C.BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature final
{
public:
	class UWBP_PalCharacterSlotButtonBase_C*      Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPalItemSlotPressType                         PressType;                                         // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_GlobalBoxPalList_C_BndEvt__WBP_GlobalBoxPalList_WBP_BoxPalListBase_K2Node_ComponentBoundEvent_0_OnLeftClickedSlot__DelegateSignature;

}

