#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_WorldSetting

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_WorldSetting.WBP_WorldSetting_C
// 0x0050 (0x0668 - 0x0618)
class UWBP_WorldSetting_C final : public UPalUIWorldSettingBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0618(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_69;                                          // 0x0620(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CommonWaiting_C*                   WBP_CommonWaiting;                                 // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Title_WorldMenu_Head_C*            WBP_Title_WorldMenu_Head;                          // 0x0630(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Title_WorldSettings_C*             WBP_Title_WorldSettings;                           // 0x0638(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FDataTableRowHandle                    WaitingSaveMsgID;                                  // 0x0640(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          Is_New_World;                                      // 0x0650(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_651[0x7];                                      // 0x0651(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_HUDDispatchParameter_WorldNameInput_C* WorldNameInputDispatchParameter;                // 0x0658(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UBP_HUDDispatchParameter_RandomizerSeedInput_C* RandomizerSeedInputDispatchParameter;      // 0x0660(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void StartNewGame(const struct FPalOptionWorldSettings& Option);
	void OpenWorldNameInputWindow();
	void OpenRandomizerSeedInputWindow();
	void OpenCheckSaveSettingDialog();
	void Open_Start_Game_Check_Dialog();
	void OnSetup();
	void OnFilteredWorldName(const class FString& NewWorldName);
	void OnCompletedSaveSetting(bool IsSuccess);
	void OnClosedWorldNameInputWindow(class UPalHUDDispatchParameterBase* Param_0);
	void OnClosedSaveSettingDialog(bool bResult);
	void OnClosedRandomizerSeedInputWindow(class UPalHUDDispatchParameterBase* Param_0);
	void OnCancelAction();
	void On_Closed_Start_Game_Dialog(bool bResult);
	void ExecuteUbergraph_WBP_WorldSetting(int32 EntryPoint);
	void Destruct();
	void Construct();
	void BndEvt__WBP_WorldSetting_WBP_Title_WorldSettings_K2Node_ComponentBoundEvent_3_OnClickedRandomizerSeedInputButton__DelegateSignature();
	void BndEvt__WBP_WorldSetting_WBP_Title_WorldSettings_K2Node_ComponentBoundEvent_2_OnClickedWorldNameInputButton__DelegateSignature();
	void BndEvt__WBP_WorldSetting_WBP_Title_WorldSettings_K2Node_ComponentBoundEvent_1_OnClickedConfirm__DelegateSignature();
	void BndEvt__WBP_WorldSetting_WBP_Title_WorldSettings_K2Node_ComponentBoundEvent_0_OnClickedCancel__DelegateSignature();

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_WorldSetting_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_WorldSetting_C")
	}
	static class UWBP_WorldSetting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_WorldSetting_C>();
	}
};
DUMPER7_ASSERTS_UWBP_WorldSetting_C;

}

