#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalItemSlotButtonBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "Pal_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalItemSlotButtonBase.WBP_PalItemSlotButtonBase_C
// 0x01A0 (0x05A8 - 0x0408)
class UWBP_PalItemSlotButtonBase_C : public UPalUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0408(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonButtonBase*                      My_Button;                                         // 0x0410(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalItemSlotBase_C*                 MyItemSlotWidget;                                  // 0x0418(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget, EPalItemSlotPressType PressType)> OnClickedButton; // 0x0420(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase)> OnMiddleClickedButton; // 0x0430(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* buttonBase, EPalItemSlotPressType PressType)> OnRightClickedButton; // 0x0440(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnHoveredButton;      // 0x0450(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnUnhoveredButton;    // 0x0460(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnFocusedWidget;      // 0x0470(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnUnFocusedWidget;    // 0x0480(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnDragged;            // 0x0490(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnDropped;            // 0x04A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnDropCanceled;       // 0x04B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          IsEnableDragDrop;                                  // 0x04C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C1[0x7];                                      // 0x04C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(int32 LiftNum, class UWBP_PalItemSlotButtonBase_C* Widget)> OnLiftedButton; // 0x04C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnFinishLiftedButton; // 0x04D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          IsDisplayingItemInfo;                              // 0x04E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsDisplayCommonItemInfoWindow;                     // 0x04E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4EA[0x6];                                      // 0x04EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnSetEmptySlot;                                    // 0x04F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnSetValidSlot;                                    // 0x0500(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          IsEnableSpreadLift;                                // 0x0510(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsUsableSlot;                                      // 0x0511(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_512[0x2];                                      // 0x0512(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPalDataTableRowName_UIInputAction     HalfLiftAction_ForPad;                             // 0x0514(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FPalDataTableRowName_UIInputAction     UseAction_ForPad;                                  // 0x051C(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FPalUIActionBindData                   HalfLiftActionHandle_ForPad;                       // 0x0524(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	struct FPalUIActionBindData                   UseActionHandle_ForPad;                            // 0x0528(0x0004)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          IsSupportedQuickMove;                              // 0x052C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsEnableQuickEquip;                                // 0x052D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_52E[0x2];                                      // 0x052E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(double MaxDurability, double NowDurability, class UWBP_PalItemSlotButtonBase_C* SelfWidget)> OnNotifyDurability; // 0x0530(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnCorruptionUpdate;                                // 0x0540(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Button)> OnRequestUseItem;     // 0x0550(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          IsShowPrice;                                       // 0x0560(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_561[0x7];                                      // 0x0561(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class UWBP_PalItemSlotButtonBase_C* Widget)> OnTriedEquipSlot;     // 0x0568(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UPalItemSlot* Slot)> OnUpdateSlot;                           // 0x0578(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FText                                   Override_Num_Count_Text;                           // 0x0588(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bShouldDisplayItemInfo;                            // 0x05A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Bind_Button_Events();
	void Construct();
	void Destruct();
	void ExecuteUbergraph_WBP_PalItemSlotButtonBase(int32 EntryPoint);
	void Focus();
	void GetDisplayDragItemNum(int32* DisplayNum);
	void GetItemAndNum(struct FPalItemAndNum* ItemAndNum);
	void GetTargetSlot(class UPalItemSlot** TargetSlot);
	void On_Hovered_Internal(class UCommonButtonBase* Button);
	void On_Right_Clicked_Internal();
	void On_Use_or_Move_Slot_Input_Pad();
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnClicked_Internal(class UCommonButtonBase* Button);
	void OnCorruptionUpdate_Internal();
	void OnDragDetected(const struct FGeometry& MyGeometry, const struct FPointerEvent& PointerEvent, class UDragDropOperation** Operation);
	void OnDragged_Internal();
	bool OnDrop(const struct FGeometry& MyGeometry, const struct FPointerEvent& PointerEvent, class UDragDropOperation* Operation);
	void OnDropCanceled_Internal(class UDragDropOperation* Operation);
	void OnDropped_Internal();
	void OnFinishLiftedButton_Internal();
	void OnHalfLiftInput_Pad();
	void OnInitialized();
	void OnLiftedButton_Internal(int32 LiftedItemNum);
	void OnMiddleClicked_Internal();
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void OnNotifyDurability_Internal(double MaxDurability, double NowDurability);
	struct FEventReply OnPreviewMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnSetEmpty_internal();
	void OnSetValid_Internal();
	void OnUnhovered_Internal(class UCommonButtonBase* Button);
	void OnUpdateSlot_Internal(class UPalItemSlot* TargetSlot);
	void RegisterButton(class UCommonButtonBase** Button);
	void RegisterItemSlotWidget(class UWBP_PalItemSlotBase_C** itemSlotWidget);
	void RegisterPadAction();
	void Setup(class UPalItemSlot* TargetSlot);
	void TryEquipSlot();
	void Unbind_Button_Events();
	void UnregisterPadAction();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PalItemSlotButtonBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PalItemSlotButtonBase_C")
	}
	static class UWBP_PalItemSlotButtonBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalItemSlotButtonBase_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PalItemSlotButtonBase_C;

}

