#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PalCharacterSlotButtonBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Pal_structs.hpp"
#include "Pal_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PalCharacterSlotButtonBase.WBP_PalCharacterSlotButtonBase_C
// 0x00C0 (0x04C8 - 0x0408)
class UWBP_PalCharacterSlotButtonBase_C : public UPalUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0408(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonButtonBase*                      My_Button;                                         // 0x0410(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_PalCharacterSlotBase_C*            MyCharacterSlotWidget;                             // 0x0418(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* Widget, EPalItemSlotPressType PressType)> OnClickedButton; // 0x0420(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* buttonBase)> OnRightClickedButton; // 0x0430(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* Widget)> OnHoveredButton; // 0x0440(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* Widget)> OnUnhoveredButton; // 0x0450(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* Widget)> OnFocusedWidget; // 0x0460(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* Widget)> OnUnFocusedWidget; // 0x0470(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* Widget)> OnDragged;       // 0x0480(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* Widget)> OnDropped;       // 0x0490(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          isDragging;                                        // 0x04A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsEnableDragDrop;                                  // 0x04A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsEnableClick;                                     // 0x04A2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4A3[0x5];                                      // 0x04A3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* SelfButton)> OnSlotSync;  // 0x04A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class UWBP_PalCharacterSlotButtonBase_C* SlotButton)> OnUpdateSlot; // 0x04B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BindButtonEvents();
	void ExecuteUbergraph_WBP_PalCharacterSlotButtonBase(int32 EntryPoint);
	void Focus();
	void GetIndividualParameter(class UPalIndividualCharacterParameter** IndividualParameter);
	void GetIsSlotSync(bool* WaitingSync);
	void GetTargetSlot(class UPalIndividualCharacterSlot** TargetSlot);
	void On_Slot_Synced();
	void OnClicked_Internal(class UCommonButtonBase* Button);
	void OnDragDetected(const struct FGeometry& MyGeometry, const struct FPointerEvent& PointerEvent, class UDragDropOperation** Operation);
	void OnDragged_Internal();
	bool OnDrop(const struct FGeometry& MyGeometry, const struct FPointerEvent& PointerEvent, class UDragDropOperation* Operation);
	void OnDropped_Internal();
	void OnHovered_Internal(class UCommonButtonBase* Button);
	void OnInitialized();
	struct FEventReply OnMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	struct FEventReply OnMouseButtonUp(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	struct FEventReply OnPreviewMouseButtonDown(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent);
	void OnRightClicked_Internal();
	void OnUnhovered_Internal(class UCommonButtonBase* Button);
	void OnUpdateSlot_Binded(class UPalIndividualCharacterSlot* TargetSlot);
	void RegisterButton(class UCommonButtonBase** Button);
	void RegisterCharacterSlotWidget(class UWBP_PalCharacterSlotBase_C** characterSlotWidget);
	void Setup(class UPalIndividualCharacterSlot* TargetSlot);
	void SetupByCharacterID(class FName CharacterID);
	void SetupByIndividualId(const struct FPalInstanceID& IndividualId);
	void SetupBySaveParameter(const struct FPalIndividualCharacterSaveParameter& SaveParam);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PalCharacterSlotButtonBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PalCharacterSlotButtonBase_C")
	}
	static class UWBP_PalCharacterSlotButtonBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PalCharacterSlotButtonBase_C>();
	}
};
DUMPER7_ASSERTS_UWBP_PalCharacterSlotButtonBase_C;

}

